[profile.default]
# Source files and output directory
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./post_deployments"}]

# Compilation and optimization settings
solc_version = '0.8.26'
evm_version = "cancun"
optimize = true

# Optimizer settings
optimizer_runs = 50 # Normal circumcentence we would use eternal storage or even 2535 diamond for metapool
via_ir = true

# Debug settings
debug = false

# RPC settings for local network interactions
rpc_url = "http://127.0.0.1:8545"

# Enable Foreign Function Interface (FFI)
ffi = true
